export const ORDER_CREATE = {
	REQUEST: "ORDER_CREATE_REQUEST",
	SUCCESS: "ORDER_CREATE_SUCCESS",
	FAIL: "ORDER_CREATE_FAIL",
	RESET: "ORDER_CREATE_RESET",
};

export const ORDER_DETAILS = {
	REQUEST: "ORDER_DETAILS_REQUEST",
	SUCCESS: "ORDER_DETAILS_SUCCESS",
	FAIL: "ORDER_DETAILS_FAIL",
};

export const ORDER_PAY = {
	REQUEST: "ORDER_PAY_REQUEST",
	SUCCESS: "ORDER_PAY_SUCCESS",
	FAIL: "ORDER_PAY_FAIL",
	RESET: "ORDER_PAY_RESET",
};

export const ORDER_MINE_LIST = {
	REQUEST: "ORDER_MINE_LIST_REQUEST",
	SUCCESS: "ORDER_MINE_LIST_SUCCESS",
	FAIL: "ORDER_MINE_LIST_FAIL",
};
