export const PRODUCT_LIST = {
	REQUEST: "PRODUCT_LIST_REQUEST",
	SUCCESS: "PRODUCT_LIST_SUCCESS",
	FAIL: "PRODUCT_LIST_FAIL",
};

export const PRODUCT_DETAILS = {
	REQUEST: "PRODUCT_DETAILS_REQUEST",
	SUCCESS: "PRODUCT_DETAILS_SUCCESS",
	FAIL: "PRODUCT_DETAILS_FAIL",
};

export const PRODUCT_CATEGORY_LIST = {
	REQUEST: "PRODUCT_CATEGORY_LIST_REQUEST",
	SUCCESS: "PRODUCT_CATEGORY_LIST_SUCCESS",
	FAIL: "PRODUCT_CATEGORY_LIST_FAIL",
};
