export const USER_SIGNIN = {
	REQUEST: "USER_SIGNIN_REQUEST",
	SUCCESS: "USER_SIGNIN_SUCCESS",
	FAIL: "USER_SIGNIN_FAIL",
};

export const USER_REGISTER = {
	REQUEST: "USER_REGISTER_REQUEST",
	SUCCESS: "USER_REGISTER_SUCCESS",
	FAIL: "USER_REGISTER_FAIL",
};

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_DETAILS = {
	REQUEST: "USER_DETAILS_REQUEST",
	SUCCESS: "USER_DETAILS_SUCCESS",
	FAIL: "USER_DETAILS_FAIL",
};

export const USER_UPDATE_PROFILE = {
	REQUEST: "USER_UPDATE_PROFILE_REQUEST",
	SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
	FAIL: "USER_UPDATE_PROFILE_FAIL",
	RESET: "USER_UPDATE_PROFILE_RESET",
};
